#pragma once

#include "game/CharacterState.h"

#include <cstdint>
#include <optional>
#include <string>
#include <string_view>

namespace OpenYAMM::Game
{
enum class PortraitId : uint16_t
{
    Invalid = 0,
    Normal = 1,
    Cursed = 2,
    Weak = 3,
    Sleep = 4,
    Fear = 5,
    Drunk = 6,
    Insane = 7,
    Poisoned = 8,
    Diseased = 9,
    Paralyzed = 10,
    Unconscious = 11,
    Petrified = 12,
    Blink = 13,
    Wink = 14,
    MouthOpenRandom = 15,
    PurseLipsRandom = 16,
    LookUp = 17,
    LookRight = 18,
    LookLeft = 19,
    LookDown = 20,
    Talk = 21,
    MouthOpenWide = 22,
    MouthOpenA = 23,
    MouthOpenO = 24,
    No = 25,
    Yes = 27,
    PurseLips1 = 29,
    PurseLips2 = 30,
    PurseLips3 = 31,
    AvoidDamage = 33,
    DamageReceivedMinor = 34,
    DamageReceivedModerate = 35,
    DamageReceivedMajor = 36,
    Smile = 37,
    WideSmile = 38,
    Sad = 39,
    CastSpell = 40,
    Portrait41 = 41,
    Portrait42 = 42,
    Portrait43 = 43,
    Portrait44 = 44,
    Portrait45 = 45,
    Scared = 46,
    Portrait47 = 47,
    Portrait48 = 48,
    Portrait49 = 49,
    Portrait50 = 50,
    Portrait51 = 51,
    Portrait52 = 52,
    Portrait53 = 53,
    Portrait54 = 54,
    Portrait55 = 55,
    Portrait56 = 56,
    Portrait57 = 57,
    WakeUp = 58,
    Dead = 98,
    Eradicated = 99,
};

enum class FaceAnimationId : uint16_t
{
    KillSmallEnemy = 1,
    KillBigEnemy = 2,
    StoreClosed = 3,
    DisarmTrap = 4,
    TrapExploded = 5,
    AvoidDamage = 6,
    IdentifyUseless = 7,
    IdentifyGreat = 8,
    IdentifyFail = 9,
    RepairItem = 10,
    RepairFail = 11,
    SetQuickSpell = 12,
    CantRestHere = 13,
    SkillIncreased = 14,
    CantCarry = 15,
    MixPotion = 16,
    PotionExplode = 17,
    DoorLocked = 18,
    WontBudge = 19,
    CantLearnSpell = 20,
    LearnSpell = 21,
    Hello = 22,
    HelloNight = 23,
    Damaged = 24,
    Weak = 25,
    Afraid = 26,
    Poisoned = 27,
    Diseased = 28,
    Insane = 29,
    Cursed = 30,
    Drunk = 31,
    Unconscious = 32,
    Death = 33,
    Stoned = 34,
    Eradicated = 35,
    DrinkPotion = 36,
    ReadScroll = 37,
    NotEnoughGold = 38,
    CantEquip = 39,
    ItemBrokenStolen = 40,
    SpellPointsDrained = 41,
    Aged = 42,
    SpellFailed = 43,
    DamagedParty = 44,
    Tired = 45,
    EnterDungeon = 46,
    LeaveDungeon = 47,
    AlmostDead = 48,
    CastSpell = 49,
    Shoot = 50,
    AttackHit = 51,
    AttackMiss = 52,
};

std::optional<PortraitId> portraitIdFromName(std::string_view name);
std::optional<FaceAnimationId> faceAnimationIdFromName(std::string_view name);
std::optional<PortraitId> portraitIdForCondition(CharacterCondition condition);
bool isConditionPortrait(PortraitId portraitId);
bool isDamagePortrait(PortraitId portraitId);
std::string portraitIdName(PortraitId portraitId);
}
