#pragma once

#include <cstdint>

namespace OpenYAMM::Game
{
enum class SpeechId : uint16_t
{
    None = 0,
    DisarmTrap,
    StoreClosed,
    TrapExploded,
    SelectCharacter,
    IdentifyWeakItem,
    IdentifyGreatItem,
    IdentifyFailItem,
    RepairSuccess,
    RepairFail,
    SetQuickSpell,
    Hungry,
    DamageMinor,
    DamageMajor,
    Dying,
    Drunk,
    Insane,
    Poisoned,
    Cursed,
    Falling,
    CantRestHere,
    NotEnoughGold,
    InventoryRoom,
    PotionSuccess,
    PotionFail,
    DoorLocked,
    LearnSpell,
    CantLearnSpell,
    CantEquip,
    HelloDay,
    HelloEvening,
    HelloHouse,
    KillStrongEnemy,
    KillWeakEnemy,
    LastPersonStanding,
    LeaveDungeon,
    EnterDungeon,
    Yes,
    ThankYou,
    Indignant,
    Yell,
    AttackHit,
    AttackMiss,
    Shoot,
    CastSpell,
    DamagedParty,
    FoundItem,
    SkillIncreased,
    QuestGot,
    AwardGot,
    TempleHeal,
    TempleDonate,
    TravelBoat,
    TravelHorse,
    ShopIdentify,
    ShopRepair,
    AlreadyIdentified,
    ItemSold,
    WrongShop,
    BankDeposit,
    LevelUp,
};
}
