;----------------------------------------------------------------
;	damageType.inc
;	Jeff Leggett
;
;
;	List of all damage types.... These directly correspond
;	to the damage types listed in assets.h
;----------------------------------------------------------------


#number	DT_UNSPECIFIED		= 0

#number	DT_MELEE			= 1
#number	DT_WEAPON			= 2
#number	DT_PROJECTILE		= 4
#number	DT_SPELL			= 8
#number	DT_CHOKE			= 16
#number	DT_IMPACT			= 32
#number	DT_BURN				= 64
#number	DT_FREEZE			= 128
#number	DT_ELECTROCUTE		= 256
#number	DT_ENDLESS_FALL		= 512
#number	DT_EXPLODE			= 1024
#number	DT_DEATH			= 2048
#number	DT_NORMAL			= 4096

