;-----------------------------------
;	LichLabScene.inc
;	by SJR
;	11-10-01
;	Purpose:basic triggers for LichLab
;			cutscene
;-----------------------------------

;----------------------
:InitLichLabScenes
;----------------------
	AddTrigger Scene0, OnScene0
	AddTrigger Scene1, OnScene1
	AddTrigger Scene2, OnScene2
	AddTrigger Scene3, OnScene3
	AddTrigger Scene4, OnScene4
	AddTrigger Scene5, OnScene5
	AddTrigger Scene6, OnScene6

	Exit 1

;----------------------
:OnScene0
;----------------------
	Exit 1
;----------------------
:OnScene1
;----------------------
	Exit 1
;----------------------
:OnScene2
;----------------------
	Exit 1
;----------------------
:OnScene3
;----------------------
	Exit 1
;----------------------
:OnScene4
;----------------------
	Exit 1
;----------------------
:OnScene5
;----------------------
	Exit 1
;----------------------
:OnScene6
;----------------------
	Exit 1