DONT_INCLUDE_THIS_FILE
;;;ONLY COPY-PASTE FROM HERE

#string		SPELL_INTERVENTION = "fg spell-divine intervention"
#string		SPELL_ELEMPROTECTION = "fg spell-elemental protection"
#string		SPELL_EYEOFTHESTORM = "fg spell-eye of storm"
#string		SPELL_FEATHERFALL = "fg spell-feather fall"
#string		SPELL_RESISTDEATH = "fg spell-resistance to death"
#string		SPELL_SHAREDLIFE = "fg spell-shared life"

#string		SPELL_ELEMBLAST = "elemental blast"
#string		SPELL_ARMOR = "spell-armor"
#string		SPELL_COLUMNOFFIRE = "spell-column of fire"
#string		SPELL_DARKGRASP = "spell-dark grasp"
#string		SPELL_DEATHTOUCH = "spell-death's touch"
#string		SPELL_DISEASE = "spell-disease"
#string		SPELL_ENRAGE = "spell-enrage"
#string		SPELL_METEOR = "spell-meteor shower"
#string		SPELL_PARALYZE = "spell-paralyze"
#string		SPELL_POISON = "spell-poison"
#string		SPELL_POISONCLOUD = "spell-poison cloud"
#string		SPELL_SKULLCURSE = "spell-skullcurse"
#string		SPELL_SOULDRINKER = "spell-souldrinker"
#string		SPELL_SPELLREAVER = "spell-spell reaver"
#string		SPELL_TOWNPORTAL = "spell-town portal"
#string		SPELL_TRANSFUSION = "spell-transfusion"
#string		SPELL_TURNUNDEAD = "spell-turn undead"

#string		SPELL_BLUEDOTS = "bluedots"
#string		SPELL_GREENDOTS = "greenyeldots"
#string		SPELL_REDDOTS = "redyeldots"
#string		SPELL_FIREFLY = "firefly"
#string		SPELL_BUGS = "bugs"
#string		SPELL_SPARKLIES = "sparklies"
#string		SPELL_SMOKE = "smoke"
#string		SPELL_SMOKESTACK = "smokestack"
#string		SPELL_DRAGONSMOKE = "dragon smoke"
#string		SPELL_GREATERDEMON = "GreaterDemon"
#string		SPELL_NJAMLIGHT = "Njam lightball for cutscene"

#string		SPELL_BLACKSMOKE = "blacksmoke"
#string		SPELL_BLUEFIRE = "fireblue"
#string		SPELL_MIST = "mist"
#string		SPELL_OVAL = "oval"
#string		SPELL_SPIRIT = "spirit"

;--------------------------------------------
:CacheAllSpells
;--------------------------------------------
	CacheClientFX 		SPELL_INTERVENTION
	CacheClientFX 		SPELL_ELEMPROTECTION
	CacheClientFX 		SPELL_EYEOFTHESTORM
	CacheClientFX 		SPELL_FEATHERFALL
	CacheClientFX 		SPELL_RESISTDEATH
	CacheClientFX 		SPELL_SHAREDLIFE

	CacheClientFX 		SPELL_ELEMBLAST
	CacheClientFX 		SPELL_ARMOR
	CacheClientFX 		SPELL_COLUMNOFFIRE
	CacheClientFX 		SPELL_DARKGRASP
	CacheClientFX 		SPELL_DEATHTOUCH
	CacheClientFX 		SPELL_DISEASE
	CacheClientFX 		SPELL_ENRAGE
	CacheClientFX 		SPELL_METEOR
	CacheClientFX 		SPELL_PARALYZE
	CacheClientFX 		SPELL_POISON
	CacheClientFX 		SPELL_POISONCLOUD
	CacheClientFX 		SPELL_SKULLCURSE
	CacheClientFX 		SPELL_SOULDRINKER
	CacheClientFX 		SPELL_SPELLREAVER
	CacheClientFX 		SPELL_TOWNPORTAL
	CacheClientFX 		SPELL_TRANSFUSION
	CacheClientFX 		SPELL_TURNUNDEAD

	CacheClientFX 		SPELL_BLUEDOTS
	CacheClientFX 		SPELL_GREENDOTS
	CacheClientFX 		SPELL_REDDOTS
	CacheClientFX 		SPELL_FIREFLY
	CacheClientFX 		SPELL_BUGS
	CacheClientFX 		SPELL_SPARKLIES
	CacheClientFX 		SPELL_SMOKE
	CacheClientFX 		SPELL_SMOKESTACK
	CacheClientFX 		SPELL_DRAGONSMOKE
	CacheClientFX 		SPELL_GREATERDEMON
	CacheClientFX 		SPELL_NJAMLIGHT

	CacheClientFX		SPELL_BLACKSMOKE
	CacheClientFX		SPELL_BLUEFIRE
	CacheClientFX		SPELL_MIST
	CacheClientFX		SPELL_OVAL
	CacheClientFX		SPELL_SPIRIT

	Exit 1